version: '3'
services:
  llm-hackathon:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit
    ports:
      - 8501:8501
    volumes:
      - type: bind
        source: "./"
        target: "/app"
    env_file:
      - ~/.env
